[keepa]
api_key = "ach00vu874jtpkb4pbom0bqh37end3hrs19vlqk003g6ibegfh2q27lpb1vdfhhj"
domain = "JP"

[selection]
min_profit = 300
min_roi = 0.3
max_avg_rank_90d = 100000
block_amazon_current_buybox = true
debug_no_fba_fee = false
